"""
Tetrapeptide transition-path-sampling experiment with a shared sequence-conditioned
proposal model and two Take 3 adaptation modes on held-out peptides.

This runner assumes preprocessed per-peptide torsion files produced by
`prep_tetrapeptide_data.py` or equivalent npz files with:
  - angles: (n_frames, 4, 7) or (n_frames, n_torsions)
or
  - features: (n_frames, 2 * n_torsions)

It uses:
  - a leave-one-out shared proposal model trained on the other loaded peptides
    with short-history conditioning (current frame, two previous frames, and
    the corresponding deltas)
  - a reference 10-state MSM built from the held-out peptide trajectory
  - the rarest non-zero flux start/end state pair, following the MDGen paper
  - reward-only endpoint conditioning toward the chosen end state
  - two twist variants on the held-out peptide:
      * Oracle: trained from real held-out peptide windows
      * Self: trained from unconditional windows generated by the shared proposal itself

Metrics:
  - JSD of visited states vs conditioned reference MSM paths
  - valid path rate
  - average path probability under the reference MSM
"""

import argparse
import math
import os
import sys
import time
from collections import OrderedDict
import numpy as np
from scipy.special import logsumexp

try:
    import torch
    import torch.nn as nn
    import torch.optim as optim
except ImportError as exc:
    raise SystemExit(
        "run_exp6_tetrapeptide_tps.py requires PyTorch. Install torch to train the tetrapeptide score and twist models."
    ) from exc

DEVICE = "mps" if torch.backends.mps.is_available() else "cpu"
print(f"Using device: {DEVICE}")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)
EXPERIMENTS_DIR = os.path.join(ROOT, "experiments")
if EXPERIMENTS_DIR not in sys.path:
    sys.path.insert(0, EXPERIMENTS_DIR)

from updated_code.common import systematic_resample, compute_ess, build_future_reward_targets, sample_row_indices, mean_std, save_json
from updated_code.fixed_twist import train_positive_twist_kl, PositiveNNTwist
from updated_code.tetrapeptide_tps import (
    MAX_RESIDUES,
    choose_start_end_states,
    compute_tps_metrics,
    discretize_feature_paths,
    endpoint_log_reward_factory,
    fit_reference_state_model,
    load_mdgen_like_path_file,
    load_tetrapeptide_directory,
    sample_conditioned_state_paths,
    sample_start_features,
    select_start_state_windows,
)

from updated_code.learned_scores import ScoreNet


RESULTS_DIR = os.path.join(os.path.dirname(__file__), "results")
DEFAULT_OUTPUT = os.path.join(RESULTS_DIR, "run_exp6_tetrapeptide_tps.json")
AA_ALPHABET = "ACDEFGHIKLMNPQRSTVWY"
AA_TO_INDEX = {aa: idx for idx, aa in enumerate(AA_ALPHABET)}
SEQ_FEATURE_DIM = MAX_RESIDUES * len(AA_ALPHABET)


def parse_args():
    parser = argparse.ArgumentParser(description="Tetrapeptide TPS benchmark with a shared sequence-conditioned proposal model.")
    parser.add_argument("--data-dir", required=True, help="Directory of per-peptide torsion npz files.")
    parser.add_argument("--split-csv", default=None, help="Optional CSV of peptide names to evaluate, e.g. MDGen 4AA_test.csv.")
    parser.add_argument("--output-json", default=DEFAULT_OUTPUT)
    parser.add_argument("--device", default=DEVICE)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--max-peptides", type=int, default=None)
    parser.add_argument("--test-peptide", default=None, help="Optional held-out peptide name. If omitted, run leave-one-out over all loaded peptides.")
    parser.add_argument("--max-test-peptides", type=int, default=5, help="If --test-peptide is omitted, evaluate on at most this many held-out peptides.")
    parser.add_argument("--state-pair-modes", nargs="+", default=["medium", "hard"], choices=["hard", "medium", "easy"],
                        help="State-pair difficulty settings to evaluate on each held-out peptide.")
    parser.add_argument("--horizon-frames", type=int, default=100)
    parser.add_argument("--lag-frames", type=int, default=10)
    parser.add_argument("--path-length", type=int, default=10, help="Discrete path length for MSM evaluation.")
    parser.add_argument("--n-states", type=int, default=10)
    parser.add_argument("--n-tica-dims", type=int, default=5)
    parser.add_argument("--score-epochs", type=int, default=12000)
    parser.add_argument("--twist-epochs", type=int, default=7000)
    parser.add_argument("--hidden-dim", type=int, default=384)
    parser.add_argument("--n-layers", type=int, default=5)
    parser.add_argument("--max-pairs", type=int, default=600000)
    parser.add_argument("--score-batch-size", type=int, default=512)
    parser.add_argument("--score-lr", type=float, default=5e-4)
    parser.add_argument("--twist-lr", type=float, default=5e-4)
    parser.add_argument("--proposal-history-frames", type=int, default=3,
                        help="Number of recent frames to condition the shared proposal on, including the current frame.")
    parser.add_argument("--balanced-pair-sampling", action="store_true", default=True,
                        help="Sample shared score-training pairs approximately uniformly across training peptides.")
    parser.add_argument("--unbalanced-pair-sampling", action="store_false", dest="balanced_pair_sampling",
                        help="Disable peptide-balanced pair sampling and subsample globally instead.")
    parser.add_argument("--max-ref-windows", type=int, default=None)
    parser.add_argument("--self-ref-windows", type=int, default=20000, help="Number of shared-model rollout windows for self-trained test-time twists.")
    parser.add_argument("--self-ref-batch-size", type=int, default=256,
                        help="Batch size for unconditional learned-proposal rollouts used to build self-reference windows.")
    parser.add_argument("--window-stride", type=int, default=1)
    parser.add_argument("--reward-lambda", type=float, default=12.0)
    parser.add_argument("--n-trials", type=int, default=8)
    parser.add_argument("--K", type=int, default=256)
    parser.add_argument("--M", type=int, default=32)
    parser.add_argument("--S-max", type=float, default=1.5)
    parser.add_argument("--n-diff-steps", type=int, default=30)
    parser.add_argument("--reference-paths", type=int, default=2000)
    parser.add_argument("--gt-samples", type=int, default=10000)
    parser.add_argument("--mdgen-paths-dir", default=None, help="Optional directory with external MDGen path files for direct metric comparison.")
    parser.add_argument("--skip-oracle-twist", action="store_true",
                        help="Skip the oracle-twist ablation to reduce runtime.")
    return parser.parse_args()


def encode_sequence_features(sequence):
    seq = str(sequence).upper()
    out = np.zeros((MAX_RESIDUES, len(AA_ALPHABET)), dtype=np.float64)
    for idx, aa in enumerate(seq[:MAX_RESIDUES]):
        aa_idx = AA_TO_INDEX.get(aa)
        if aa_idx is not None:
            out[idx, aa_idx] = 1.0
    return out.reshape(-1)


def peptide_conditioning_sequence(peptide):
    name = peptide.get("name")
    if name is not None:
        return str(name).upper()
    sequence = peptide.get("sequence")
    if sequence is not None:
        return str(sequence).upper()
    return ""


def prepare_peptide_features(peptide):
    features = np.asarray(peptide["features"], dtype=np.float64)
    feature_mask = None
    if peptide.get("mask") is not None:
        feature_mask = np.repeat(np.asarray(peptide["mask"], dtype=np.float64).reshape(-1), 2)
        features = features * feature_mask[None, :]
    return features, feature_mask


def _clone_model_state(model):
    return OrderedDict((key, value.detach().cpu().clone()) for key, value in model.state_dict().items())


def _restore_model_state(model, state):
    model.load_state_dict(state)


def _model_parameters_are_finite(model):
    return all(torch.isfinite(param).all().item() for param in model.parameters())


def _reset_optimizer_state(optimizer):
    optimizer.state.clear()


def _halve_optimizer_lr(optimizer, min_lr=1e-5):
    new_lr = None
    for group in optimizer.param_groups:
        group["lr"] = max(float(group["lr"]) * 0.5, float(min_lr))
        new_lr = group["lr"]
    return new_lr


class SequenceConditionalScore:
    def __init__(self, model, dim, context_dim, seq_dim, device="cpu", clip=15.0):
        self.model = model
        self.dim = dim
        self.context_dim = context_dim
        self.seq_dim = seq_dim
        self.device = device
        self.clip = clip


def _reshape_history_array(x):
    x = np.asarray(x, dtype=np.float64)
    if x.ndim == 1:
        return x.reshape(1, -1)
    return x.reshape(len(x), -1)


def build_history_context(x_curr, prev_frames=None, history_frames=2):
    x_curr = np.asarray(x_curr, dtype=np.float64)
    if history_frames < 1:
        raise ValueError("history_frames must be at least 1.")
    x_curr = _reshape_history_array(x_curr)

    prev_frames = [] if prev_frames is None else list(prev_frames)
    history = [x_curr]
    last = x_curr
    for idx in range(history_frames - 1):
        frame = prev_frames[idx] if idx < len(prev_frames) else last
        if frame is None:
            arr = last
        else:
            arr = _reshape_history_array(frame)
            if len(arr) == 1 and len(x_curr) > 1:
                arr = np.tile(arr, (len(x_curr), 1))
            elif len(arr) != len(x_curr):
                raise ValueError("Previous history frames must broadcast to x_curr in build_history_context.")
        history.append(arr)
        last = arr

    deltas = [history[idx] - history[idx + 1] for idx in range(len(history) - 1)]
    return np.concatenate(history + deltas, axis=-1)


def train_sequence_conditional_score(context_data, x_next_data, seq_data, dim, context_dim, seq_dim,
                                     n_epochs=3000, batch_size=256, lr=1e-3, S_max=2.0,
                                     hidden_dim=128, n_layers=4, device="cpu", verbose=True):
    context_data = np.nan_to_num(np.asarray(context_data, dtype=np.float64).reshape(-1, context_dim), nan=0.0, posinf=3.0, neginf=-3.0)
    x_next_data = np.nan_to_num(np.asarray(x_next_data, dtype=np.float64).reshape(-1, dim), nan=0.0, posinf=2.0, neginf=-2.0)
    seq_data = np.nan_to_num(np.asarray(seq_data, dtype=np.float64).reshape(-1, seq_dim), nan=0.0, posinf=1.0, neginf=0.0)
    if not (len(context_data) == len(x_next_data) == len(seq_data)):
        raise ValueError("context_data, x_next_data, and seq_data must have the same number of rows.")

    model = ScoreNet(input_dim=dim + context_dim + seq_dim, output_dim=dim,
                     hidden_dim=hidden_dim, n_layers=n_layers).to(device)
    optimizer = optim.Adam(model.parameters(), lr=lr)
    scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, n_epochs)
    last_good_state = _clone_model_state(model)

    xt = torch.tensor(context_data, dtype=torch.float32, device=device)
    xtp1 = torch.tensor(x_next_data, dtype=torch.float32, device=device)
    seq_t = torch.tensor(seq_data, dtype=torch.float32, device=device)
    n = len(xt)
    losses = []

    for epoch in range(n_epochs):
        idx = torch.randint(0, n, (batch_size,), device=device)
        context_batch = xt[idx]
        x0 = xtp1[idx]
        seq_batch = seq_t[idx]

        s = torch.rand(batch_size, device=device) * (S_max - 0.01) + 0.01
        alpha = torch.exp(-s / 2.0).unsqueeze(-1)
        sigma = torch.sqrt(torch.clamp(1.0 - torch.exp(-s), min=1e-10)).unsqueeze(-1)
        eps = torch.randn_like(x0)
        xs = alpha * x0 + sigma * eps

        target = torch.clamp(torch.nan_to_num(-eps / sigma, nan=0.0, posinf=25.0, neginf=-25.0), -25.0, 25.0)
        inp = torch.clamp(torch.nan_to_num(torch.cat([xs, context_batch, seq_batch], dim=-1), nan=0.0, posinf=4.0, neginf=-4.0), -4.0, 4.0)
        score_pred = torch.clamp(torch.nan_to_num(model(inp, s), nan=0.0, posinf=25.0, neginf=-25.0), -25.0, 25.0)

        weight = sigma.squeeze(-1) ** 2
        per_sample = torch.sum((score_pred - target) ** 2, dim=-1)
        loss = torch.mean(weight * per_sample)
        if not torch.isfinite(loss):
            restored_lr = _halve_optimizer_lr(optimizer)
            _restore_model_state(model, last_good_state)
            _reset_optimizer_state(optimizer)
            if verbose:
                print(f"    [Shared Conditional] epoch {epoch+1}/{n_epochs}: non-finite loss, restoring last good state and lowering lr to {restored_lr:.2e}")
            continue

        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        grad_norm = torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        if not torch.isfinite(grad_norm):
            restored_lr = _halve_optimizer_lr(optimizer)
            _restore_model_state(model, last_good_state)
            _reset_optimizer_state(optimizer)
            optimizer.zero_grad(set_to_none=True)
            if verbose:
                print(f"    [Shared Conditional] epoch {epoch+1}/{n_epochs}: non-finite gradient, restoring last good state and lowering lr to {restored_lr:.2e}")
            continue
        optimizer.step()
        if not _model_parameters_are_finite(model):
            restored_lr = _halve_optimizer_lr(optimizer)
            _restore_model_state(model, last_good_state)
            _reset_optimizer_state(optimizer)
            if verbose:
                print(f"    [Shared Conditional] epoch {epoch+1}/{n_epochs}: non-finite parameters, restoring last good state and lowering lr to {restored_lr:.2e}")
            continue
        scheduler.step()
        last_good_state = _clone_model_state(model)
        losses.append(float(loss.item()))

        if verbose and (epoch + 1) % 500 == 0:
            print(f"    [Shared Conditional] epoch {epoch+1}/{n_epochs}: loss={loss.item():.4f}")

    model.eval()
    return model, losses


def _allocate_balanced_counts(avail_counts, total_budget):
    avail = np.asarray(avail_counts, dtype=np.int64)
    total_budget = int(min(max(total_budget, 0), int(np.sum(avail))))
    if total_budget <= 0 or len(avail) == 0:
        return np.zeros(len(avail), dtype=np.int64)

    counts = np.minimum(avail, total_budget // len(avail))
    remaining = total_budget - int(np.sum(counts))
    while remaining > 0:
        candidates = np.where(counts < avail)[0]
        if len(candidates) == 0:
            break
        for idx in candidates:
            if remaining <= 0:
                break
            counts[idx] += 1
            remaining -= 1
    return counts


def collect_shared_transition_pairs(peptides, max_pairs, rng, balanced=True, history_frames=2):
    pair_data = []
    dim = None
    context_dim = None

    for peptide in peptides:
        features, _ = prepare_peptide_features(peptide)
        if len(features) < 2:
            continue
        if dim is None:
            dim = features.shape[1]
        elif features.shape[1] != dim:
            raise ValueError("All peptides must share the same feature dimension for transferable score training.")
        pair_curr = features[:-1]
        pair_history = []
        pair_indices = np.arange(len(pair_curr))
        for lag in range(1, history_frames):
            pair_history.append(pair_curr[np.maximum(pair_indices - lag, 0)])
        pair_x = build_history_context(pair_curr, prev_frames=pair_history, history_frames=history_frames)
        pair_y = features[1:]
        if context_dim is None:
            context_dim = pair_x.shape[1]
        elif pair_x.shape[1] != context_dim:
            raise ValueError("All peptides must share the same history-context dimension.")
        seq_feat = encode_sequence_features(peptide_conditioning_sequence(peptide))
        seq_data = np.tile(seq_feat[None, :], (len(features) - 1, 1))
        pair_data.append({
            "name": peptide["name"],
            "pair_x": pair_x,
            "pair_y": pair_y,
            "seq": seq_data,
        })

    if not pair_data:
        raise ValueError("No valid transition pairs were found in the training peptide set.")

    if max_pairs is None:
        counts = np.asarray([len(item["pair_x"]) for item in pair_data], dtype=np.int64)
    elif balanced:
        counts = _allocate_balanced_counts([len(item["pair_x"]) for item in pair_data], max_pairs)
    else:
        counts = np.asarray([len(item["pair_x"]) for item in pair_data], dtype=np.int64)

    pair_x_parts = []
    pair_y_parts = []
    seq_parts = []
    sampling_counts = {}
    for item, keep_count in zip(pair_data, counts):
        if max_pairs is None:
            keep_count = len(item["pair_x"])
        keep_count = int(min(keep_count, len(item["pair_x"])))
        if keep_count <= 0:
            continue
        if keep_count < len(item["pair_x"]):
            idx = rng.choice(len(item["pair_x"]), size=keep_count, replace=False)
            pair_x_parts.append(item["pair_x"][idx])
            pair_y_parts.append(item["pair_y"][idx])
            seq_parts.append(item["seq"][idx])
        else:
            pair_x_parts.append(item["pair_x"])
            pair_y_parts.append(item["pair_y"])
            seq_parts.append(item["seq"])
        sampling_counts[item["name"]] = keep_count

    pair_x = np.concatenate(pair_x_parts, axis=0)
    pair_y = np.concatenate(pair_y_parts, axis=0)
    seq_data = np.concatenate(seq_parts, axis=0)

    if max_pairs is not None and (not balanced) and len(pair_x) > max_pairs:
        idx = rng.choice(len(pair_x), size=max_pairs, replace=False)
        pair_x = pair_x[idx]
        pair_y = pair_y[idx]
        seq_data = seq_data[idx]
        sampling_counts = {"global_subsample": int(len(pair_x))}

    meta = {
        "balanced": bool(balanced),
        "per_peptide_counts": sampling_counts,
        "total_pairs": int(len(pair_x)),
    }
    return pair_x, pair_y, seq_data, dim, context_dim, meta


def choose_test_peptides(peptides, seed, test_peptide=None, max_test_peptides=None):
    peptide_names = [peptide["name"] for peptide in peptides]
    if test_peptide is not None:
        if test_peptide not in peptide_names:
            raise ValueError(f"Requested held-out peptide {test_peptide} was not found in the loaded peptide set.")
        return [test_peptide]

    if max_test_peptides is None or len(peptide_names) <= max_test_peptides:
        return peptide_names

    rng = np.random.default_rng(seed)
    idx = rng.choice(len(peptide_names), size=max_test_peptides, replace=False)
    chosen = {peptide_names[i] for i in idx}
    return [name for name in peptide_names if name in chosen]


def conditional_score_eval(o_score, x_batch, s, context_batch, seq_batch=None):
    dim = o_score.dim
    x_arr = np.asarray(x_batch, dtype=np.float64).reshape(-1, dim)
    context_arr = np.asarray(context_batch, dtype=np.float64)
    if context_arr.ndim == 1:
        context_arr = context_arr.reshape(1, o_score.context_dim)
    else:
        context_arr = context_arr.reshape(-1, o_score.context_dim)
    if len(context_arr) == 1 and len(x_arr) > 1:
        context_arr = np.tile(context_arr, (len(x_arr), 1))
    elif len(context_arr) != len(x_arr):
        raise ValueError("x_batch and context_batch must have matching batch sizes.")

    inputs = [x_arr, context_arr]
    if getattr(o_score, "seq_dim", 0):
        if seq_batch is None:
            raise ValueError("Sequence-conditioned score evaluation requires seq_batch.")
        seq_arr = np.asarray(seq_batch, dtype=np.float64)
        if seq_arr.ndim == 1:
            seq_arr = seq_arr.reshape(1, o_score.seq_dim)
        else:
            seq_arr = seq_arr.reshape(-1, o_score.seq_dim)
        if len(seq_arr) == 1 and len(x_arr) > 1:
            seq_arr = np.tile(seq_arr, (len(x_arr), 1))
        elif len(seq_arr) != len(x_arr):
            raise ValueError("seq_batch must have matching batch size.")
        inputs.append(seq_arr)

    with torch.no_grad():
        inp = torch.tensor(
            np.concatenate(inputs, axis=-1),
            dtype=torch.float32,
            device=o_score.device,
        )
        st = torch.full((len(x_arr),), float(s), dtype=torch.float32, device=o_score.device)
        out = o_score.model(inp, st).cpu().numpy()
    return np.clip(out, -o_score.clip, o_score.clip)


def _as_float_tensor(x, device):
    if isinstance(x, torch.Tensor):
        return x.to(device=device, dtype=torch.float32)
    return torch.as_tensor(x, dtype=torch.float32, device=device)


def _build_history_context_torch(x_curr, prev_frames, history_frames, device):
    if history_frames < 1:
        raise ValueError("history_frames must be at least 1.")
    history = [x_curr]
    last = x_curr
    prev_frames = [] if prev_frames is None else list(prev_frames)
    for idx in range(history_frames - 1):
        frame = prev_frames[idx] if idx < len(prev_frames) else last
        if frame is None:
            arr = last
        else:
            arr = _as_float_tensor(frame, device)
            if arr.ndim == 1:
                arr = arr.reshape(1, -1)
            else:
                arr = arr.reshape(arr.shape[0], -1)
            if arr.shape[0] == 1 and x_curr.shape[0] > 1:
                arr = arr.repeat(x_curr.shape[0], 1)
            elif arr.shape[0] != x_curr.shape[0]:
                raise ValueError("History frames must broadcast to x_cond in reverse_step.")
        history.append(arr)
        last = arr
    deltas = [history[idx] - history[idx + 1] for idx in range(len(history) - 1)]
    return torch.cat(history + deltas, dim=-1)


def reverse_step(o_score, x_cond, n_samples, s_max, n_steps, prev_frames=None, feature_mask=None, seq_feature=None, history_frames=2):
    device = o_score.device
    x_cond_t = _as_float_tensor(x_cond, device)
    if x_cond_t.ndim == 1:
        x_cond_t = x_cond_t.reshape(1, -1)
    else:
        x_cond_t = x_cond_t.reshape(x_cond_t.shape[0], -1)
    dim = x_cond_t.shape[1]
    n_cond = x_cond_t.shape[0]

    context_t = _build_history_context_torch(
        x_cond_t,
        prev_frames=prev_frames,
        history_frames=history_frames,
        device=device,
    )
    context_rep = context_t.repeat_interleave(n_samples, dim=0)

    seq_rep = None
    if seq_feature is not None:
        seq_t = _as_float_tensor(seq_feature, device)
        if seq_t.ndim == 1:
            seq_t = seq_t.reshape(1, -1)
        else:
            seq_t = seq_t.reshape(seq_t.shape[0], -1)
        if seq_t.shape[0] == 1 and n_cond > 1:
            seq_t = seq_t.repeat(n_cond, 1)
        elif seq_t.shape[0] != n_cond:
            raise ValueError("seq_feature must broadcast to the conditioning batch size.")
        seq_rep = seq_t.repeat_interleave(n_samples, dim=0)

    ds = float(s_max) / float(n_steps)
    sqrt_ds = math.sqrt(ds)
    x = torch.randn((context_rep.shape[0], dim), dtype=torch.float32, device=device)

    mask_t = None
    if feature_mask is not None:
        mask_t = _as_float_tensor(feature_mask, device).reshape(1, dim)
        x = x * mask_t

    with torch.no_grad():
        for step in range(n_steps):
            s = max(float(s_max) - step * ds, 1e-6)
            st = torch.full((context_rep.shape[0],), s, dtype=torch.float32, device=device)
            pieces = [x, context_rep]
            if seq_rep is not None:
                pieces.append(seq_rep)
            inp = torch.cat(pieces, dim=-1)
            score = o_score.model(inp, st)
            score = torch.clamp(torch.nan_to_num(score, nan=0.0, posinf=10.0, neginf=-10.0), -10.0, 10.0)
            drift = torch.clamp(0.5 * x + score, -10.0, 10.0)
            x = x + drift * ds + torch.randn_like(x) * sqrt_ds
            x = torch.clamp(x, -2.0, 2.0)
            if mask_t is not None:
                x = x * mask_t

    x_np = x.detach().cpu().numpy()
    if n_cond == 1:
        return x_np.reshape(n_samples, dim)
    return x_np.reshape(n_cond, n_samples, dim)


def run_naive_paths(o_score, start_features, horizon_frames, s_max, n_steps, feature_mask=None, seq_feature=None):
    paths = np.zeros((len(start_features), horizon_frames + 1, start_features.shape[1]), dtype=np.float64)
    paths[:, 0] = start_features
    for t in range(horizon_frames):
        prev_frames = [paths[:, max(t - lag, 0)] for lag in range(1, getattr(o_score, "history_frames", 2))]
        paths[:, t + 1] = reverse_step(
            o_score,
            paths[:, t],
            n_samples=1,
            s_max=s_max,
            n_steps=n_steps,
            prev_frames=prev_frames,
            feature_mask=feature_mask,
            seq_feature=seq_feature,
            history_frames=getattr(o_score, "history_frames", 2),
        ).reshape(len(start_features), start_features.shape[1])
    return paths


def estimate_log_Z_from_chain(o_score, start_features, horizon_frames, endpoint_log_G, s_max, n_steps, n_samples, batch_size, rng, feature_mask=None, seq_feature=None):
    start_features = np.asarray(start_features, dtype=np.float64)
    log_rewards = np.zeros(n_samples, dtype=np.float64)
    for start in range(0, n_samples, batch_size):
        end = min(start + batch_size, n_samples)
        batch = end - start
        idx = rng.choice(len(start_features), size=batch, replace=True)
        paths = run_naive_paths(
            o_score,
            start_features[idx],
            horizon_frames=horizon_frames,
            s_max=s_max,
            n_steps=n_steps,
            feature_mask=feature_mask,
            seq_feature=seq_feature,
        )
        log_rewards[start:end] = endpoint_log_G(paths[:, -1], horizon_frames)
    return float(logsumexp(log_rewards) - np.log(n_samples))


def estimate_log_Z_from_rollouts(paths, horizon_frames, endpoint_log_G):
    paths = np.asarray(paths, dtype=np.float64)
    if paths.ndim != 3 or paths.shape[1] != horizon_frames + 1:
        raise ValueError("Expected rollout paths with shape (n_paths, horizon_frames + 1, dim).")
    log_rewards = endpoint_log_G(paths[:, -1], horizon_frames)
    return float(logsumexp(log_rewards) - np.log(len(log_rewards)))


def run_bootstrap_trial(o_score, start_features, horizon_frames, K, endpoint_log_G, s_max, n_steps, feature_mask=None, seq_feature=None):
    start_features = np.asarray(start_features, dtype=np.float64)
    if start_features.ndim == 1:
        start_features = np.tile(start_features, (K, 1))
    else:
        start_features = start_features.reshape(K, -1)
    traj = np.zeros((K, horizon_frames + 1, start_features.shape[1]), dtype=np.float64)
    traj[:, 0] = start_features
    ess_per_step = []
    log_Z = 0.0

    for t in range(1, horizon_frames + 1):
        prev_frames = [traj[:, max(t - 1 - lag, 0)] for lag in range(1, getattr(o_score, "history_frames", 2))]
        traj[:, t] = reverse_step(
            o_score,
            traj[:, t - 1],
            n_samples=1,
            s_max=s_max,
            n_steps=n_steps,
            prev_frames=prev_frames,
            feature_mask=feature_mask,
            seq_feature=seq_feature,
            history_frames=getattr(o_score, "history_frames", 2),
        ).reshape(K, start_features.shape[1])
        log_w = endpoint_log_G(traj[:, t], t) if t == horizon_frames else np.zeros(K, dtype=np.float64)
        log_Z += logsumexp(log_w) - np.log(K)
        ess_per_step.append(compute_ess(log_w))
        traj = traj[systematic_resample(log_w)]

    return {"paths": traj, "log_Z": float(log_Z), "ess_per_step": ess_per_step}


def sample_proposal_reference_windows(o_score, start_feature_pool, horizon_frames,
                                      total_paths, batch_K, s_max, n_steps, rng,
                                      feature_mask=None, seq_feature=None):
    total_paths = int(total_paths)
    batch_K = max(1, int(batch_K))
    dim = int(start_feature_pool.shape[1])
    windows = np.zeros((total_paths, horizon_frames + 1, dim), dtype=np.float32)
    written = 0
    while written < total_paths:
        cur = min(batch_K, total_paths - written)
        idx = rng.choice(len(start_feature_pool), size=cur, replace=True)
        rollout = run_naive_paths(
            o_score,
            start_feature_pool[idx],
            horizon_frames=horizon_frames,
            s_max=s_max,
            n_steps=n_steps,
            feature_mask=feature_mask,
            seq_feature=seq_feature,
        )
        windows[written:written + cur] = rollout[:cur]
        written += cur
    return windows


def run_take3_trial(o_score, twist_fn, start_features, horizon_frames, K, M, endpoint_log_G, s_max, n_steps, feature_mask=None, seq_feature=None):
    start_features = np.asarray(start_features, dtype=np.float64)
    if start_features.ndim == 1:
        start_features = np.tile(start_features, (K, 1))
    else:
        start_features = start_features.reshape(K, -1)
    traj = np.zeros((K, horizon_frames + 1, start_features.shape[1]), dtype=np.float64)
    traj[:, 0] = start_features
    log_psi_prev = np.asarray(twist_fn(start_features, 0), dtype=np.float64).reshape(K)
    log_Z = float(logsumexp(log_psi_prev) - np.log(K))
    ess_per_step = []

    for t in range(1, horizon_frames + 1):
        prev_frames = [traj[:, max(t - 1 - lag, 0)] for lag in range(1, getattr(o_score, "history_frames", 2))]
        proposals = reverse_step(
            o_score,
            traj[:, t - 1],
            n_samples=M,
            s_max=s_max,
            n_steps=n_steps,
            prev_frames=prev_frames,
            feature_mask=feature_mask,
            seq_feature=seq_feature,
            history_frames=getattr(o_score, "history_frames", 2),
        )
        log_G = endpoint_log_G(proposals.reshape(-1, start_features.shape[1]), t).reshape(K, M)
        if t < horizon_frames:
            log_twist = np.asarray(twist_fn(proposals.reshape(-1, start_features.shape[1]), t), dtype=np.float64).reshape(K, M)
        else:
            log_twist = np.zeros((K, M), dtype=np.float64)
        log_v = log_G + log_twist
        chosen, log_norm = sample_row_indices(log_v, n_draws=1)
        traj[:, t] = proposals[np.arange(K), chosen]
        log_weights = log_norm - np.log(M) - log_psi_prev
        log_psi_next = log_twist[np.arange(K), chosen] if t < horizon_frames else np.zeros(K, dtype=np.float64)

        log_Z += logsumexp(log_weights) - np.log(K)
        ess_per_step.append(compute_ess(log_weights))
        resampled = systematic_resample(log_weights)
        traj = traj[resampled]
        if t < horizon_frames:
            log_psi_prev = log_psi_next[resampled]

    return {"paths": traj, "log_Z": float(log_Z), "ess_per_step": ess_per_step}


def evaluate_tps_task_for_peptide(
    peptide_name,
    features,
    feature_mask,
    state_model,
    o_score,
    seq_feature,
    args,
    start_state,
    end_state,
    powers,
    pair_selection,
    seed_offset,
    mdgen_paths_dir=None,
):
    rng = np.random.default_rng(seed_offset)
    reference_state_paths, reference_valid, powers = sample_conditioned_state_paths(
        state_model["transition_matrix"],
        start_state,
        end_state,
        args.path_length,
        args.reference_paths,
        rng,
    )
    reference_state_paths = reference_state_paths[reference_valid]
    if len(reference_state_paths) == 0:
        raise ValueError("Conditioned MSM sampler produced no valid reference paths.")

    windows, _ = select_start_state_windows(
        features,
        state_model["labels"],
        start_state,
        horizon_frames=args.horizon_frames,
        stride=args.window_stride,
        max_windows=args.max_ref_windows,
        rng=rng,
    )
    if len(windows) == 0:
        raise ValueError(f"No windows starting from state {start_state}.")
    all_start_windows, _ = select_start_state_windows(
        features,
        state_model["labels"],
        start_state,
        horizon_frames=args.horizon_frames,
        stride=args.window_stride,
        max_windows=None,
        rng=rng,
    )

    endpoint_log_G = endpoint_log_reward_factory(
        state_model["tica_model"],
        state_model["state_centers"],
        end_state,
        horizon_frames=args.horizon_frames,
        lam=args.reward_lambda,
        mode="soft_state",
    )
    future_targets_oracle = build_future_reward_targets(windows, args.horizon_frames, endpoint_log_G)
    start_feature_pool = features[state_model["labels"] == start_state]
    empirical_log_Z = float(
        logsumexp(endpoint_log_G(all_start_windows[:, -1], args.horizon_frames)) - np.log(len(all_start_windows))
    )

    twist_oracle = None
    oracle_twist_time = None
    if not args.skip_oracle_twist:
        print(f"Training Take 3 oracle twist ({pair_selection['mode']})...")
        t0 = time.time()
        twist_oracle_model, _ = train_positive_twist_kl(
            windows,
            future_targets_oracle,
            dim=features.shape[1],
            T=args.horizon_frames,
            n_epochs=args.twist_epochs,
            lr=args.twist_lr,
            hidden_dim=args.hidden_dim,
            n_layers=max(args.n_layers - 1, 2),
            device=args.device,
        )
        twist_oracle = PositiveNNTwist(twist_oracle_model, dim=features.shape[1], device=args.device)
        oracle_twist_time = time.time() - t0
        print(f"  Oracle twist training time: {oracle_twist_time:.1f}s")

    print(f"Generating unconditional learned-proposal self-reference windows ({pair_selection['mode']})...")
    self_ref_rng = np.random.default_rng(seed_offset + 5000)
    self_ref_windows = sample_proposal_reference_windows(
        o_score,
        start_feature_pool,
        horizon_frames=args.horizon_frames,
        total_paths=max(1, args.self_ref_windows),
        batch_K=max(1, args.self_ref_batch_size),
        s_max=args.S_max,
        n_steps=args.n_diff_steps,
        rng=self_ref_rng,
        feature_mask=feature_mask,
        seq_feature=seq_feature,
    )
    self_future_targets = build_future_reward_targets(self_ref_windows, args.horizon_frames, endpoint_log_G)

    print(f"Training Take 3 self-trained twist ({pair_selection['mode']})...")
    t0 = time.time()
    twist_self_model, _ = train_positive_twist_kl(
        self_ref_windows,
        self_future_targets,
        dim=features.shape[1],
        T=args.horizon_frames,
        n_epochs=args.twist_epochs,
        lr=args.twist_lr,
        hidden_dim=args.hidden_dim,
        n_layers=max(args.n_layers - 1, 2),
        device=args.device,
    )
    twist_self = PositiveNNTwist(twist_self_model, dim=features.shape[1], device=args.device)
    self_twist_time = time.time() - t0
    print(f"  Self twist training time: {self_twist_time:.1f}s")

    learned_log_Z = estimate_log_Z_from_rollouts(
        self_ref_windows,
        horizon_frames=args.horizon_frames,
        endpoint_log_G=endpoint_log_G,
    )

    num_paths = args.K * args.n_trials
    start_features, _ = sample_start_features(
        features,
        state_model["labels"],
        start_state,
        num_paths,
        rng,
    )

    print(f"Generating NaiveDiffusion paths ({pair_selection['mode']})...")
    naive_paths = run_naive_paths(
        o_score,
        start_features,
        horizon_frames=args.horizon_frames,
        s_max=args.S_max,
        n_steps=args.n_diff_steps,
        feature_mask=feature_mask,
        seq_feature=seq_feature,
    )
    naive_state_paths = discretize_feature_paths(
        naive_paths,
        state_model["tica_model"],
        state_model["state_centers"],
        lag_frames=args.lag_frames,
        path_length=args.path_length,
    )
    naive_trial_log_z = []
    for trial in range(args.n_trials):
        trial_paths = naive_paths[trial * args.K:(trial + 1) * args.K]
        naive_trial_log_z.append(
            estimate_log_Z_from_rollouts(
                trial_paths,
                horizon_frames=args.horizon_frames,
                endpoint_log_G=endpoint_log_G,
            )
        )

    bootstrap_trials = []
    bootstrap_paths = []
    take3_oracle_trials = []
    take3_oracle_paths = []
    take3_self_trials = []
    take3_self_paths = []

    for trial in range(args.n_trials):
        start_batch = start_features[trial * args.K:(trial + 1) * args.K]
        bootstrap_out = run_bootstrap_trial(
            o_score,
            start_batch,
            horizon_frames=args.horizon_frames,
            K=args.K,
            endpoint_log_G=endpoint_log_G,
            s_max=args.S_max,
            n_steps=args.n_diff_steps,
            feature_mask=feature_mask,
            seq_feature=seq_feature,
        )
        bootstrap_trials.append(bootstrap_out)
        bootstrap_paths.append(bootstrap_out["paths"])

        if twist_oracle is not None:
            take3_oracle_out = run_take3_trial(
                o_score,
                twist_oracle,
                start_batch,
                horizon_frames=args.horizon_frames,
                K=args.K,
                M=args.M,
                endpoint_log_G=endpoint_log_G,
                s_max=args.S_max,
                n_steps=args.n_diff_steps,
                feature_mask=feature_mask,
                seq_feature=seq_feature,
            )
            take3_oracle_trials.append(take3_oracle_out)
            take3_oracle_paths.append(take3_oracle_out["paths"])

        take3_self_out = run_take3_trial(
            o_score,
            twist_self,
            start_batch,
            horizon_frames=args.horizon_frames,
            K=args.K,
            M=args.M,
            endpoint_log_G=endpoint_log_G,
            s_max=args.S_max,
            n_steps=args.n_diff_steps,
            feature_mask=feature_mask,
            seq_feature=seq_feature,
        )
        take3_self_trials.append(take3_self_out)
        take3_self_paths.append(take3_self_out["paths"])

    bootstrap_paths = np.concatenate(bootstrap_paths, axis=0)
    take3_self_paths = np.concatenate(take3_self_paths, axis=0)
    has_oracle_paths = len(take3_oracle_paths) > 0
    take3_oracle_paths_arr = None
    if has_oracle_paths:
        take3_oracle_paths_arr = np.concatenate(take3_oracle_paths, axis=0)

    bootstrap_state_paths = discretize_feature_paths(
        bootstrap_paths,
        state_model["tica_model"],
        state_model["state_centers"],
        lag_frames=args.lag_frames,
        path_length=args.path_length,
    )
    take3_self_state_paths = discretize_feature_paths(
        take3_self_paths,
        state_model["tica_model"],
        state_model["state_centers"],
        lag_frames=args.lag_frames,
        path_length=args.path_length,
    )
    take3_oracle_state_paths = None
    if has_oracle_paths:
        take3_oracle_state_paths = discretize_feature_paths(
            take3_oracle_paths_arr,
            state_model["tica_model"],
            state_model["state_centers"],
            lag_frames=args.lag_frames,
            path_length=args.path_length,
        )

    task_result = {
        "pair_selection": pair_selection,
        "start_state": int(start_state),
        "end_state": int(end_state),
        "reference_flux": float(state_model["stationary"][start_state] * state_model["transition_matrix"][start_state, end_state]),
        "reference_metrics": {
            "num_paths": int(len(reference_state_paths)),
            "valid_path_rate": float(np.mean(reference_valid)),
        },
        "ground_truth": {
            "empirical_log_Z_from_reference_windows": empirical_log_Z,
            "learned_proposal_log_Z": learned_log_Z,
        },
        "twist_training": {
            "oracle_ref_windows": int(len(windows)),
            "oracle_training_time_sec": None if oracle_twist_time is None else float(oracle_twist_time),
            "self_ref_windows": int(len(self_ref_windows)),
            "self_training_time_sec": float(self_twist_time),
            "self_ref_source": "unconditional_learned_proposal_rollouts",
        },
        "methods": {
            "NaiveDiffusion": {
                "num_paths": int(len(naive_paths)),
                "log_Z": mean_std(naive_trial_log_z),
                "metrics": compute_tps_metrics(
                    reference_state_paths,
                    naive_state_paths,
                    state_model["transition_matrix"],
                    powers,
                    start_state=start_state,
                    end_state=end_state,
                ),
            },
            "Bootstrap": {
                "num_paths": int(len(bootstrap_paths)),
                "log_Z": mean_std([x["log_Z"] for x in bootstrap_trials]),
                "ess": mean_std([np.mean(x["ess_per_step"]) for x in bootstrap_trials]),
                "metrics": compute_tps_metrics(
                    reference_state_paths,
                    bootstrap_state_paths,
                    state_model["transition_matrix"],
                    powers,
                    start_state=start_state,
                    end_state=end_state,
                ),
            },
            "Take3-SelfTwist": {
                "num_paths": int(len(take3_self_paths)),
                "log_Z": mean_std([x["log_Z"] for x in take3_self_trials]),
                "ess": mean_std([np.mean(x["ess_per_step"]) for x in take3_self_trials]),
                "metrics": compute_tps_metrics(
                    reference_state_paths,
                    take3_self_state_paths,
                    state_model["transition_matrix"],
                    powers,
                    start_state=start_state,
                    end_state=end_state,
                ),
            },
        },
    }
    if take3_oracle_trials:
        task_result["methods"]["Take3-OracleTwist"] = {
            "num_paths": int(len(take3_oracle_paths_arr)),
            "log_Z": mean_std([x["log_Z"] for x in take3_oracle_trials]),
            "ess": mean_std([np.mean(x["ess_per_step"]) for x in take3_oracle_trials]),
            "metrics": compute_tps_metrics(
                reference_state_paths,
                take3_oracle_state_paths,
                state_model["transition_matrix"],
                powers,
                start_state=start_state,
                end_state=end_state,
            ),
        }

    external = maybe_eval_external_mdgen(
        path_dir=mdgen_paths_dir,
        peptide_name=peptide_name,
        tica_model=state_model["tica_model"],
        state_centers=state_model["state_centers"],
        path_length=args.path_length,
        reference_paths=reference_state_paths,
        T_ref=state_model["transition_matrix"],
        powers=powers,
    )
    if external is not None:
        task_result["methods"]["MDGenExternal"] = external

    return task_result


def maybe_eval_external_mdgen(path_dir, peptide_name, tica_model, state_centers, path_length, reference_paths, T_ref, powers):
    if path_dir is None:
        return None
    for suffix in (".npz", "_paths.npz", "_samples.npz"):
        candidate = os.path.join(path_dir, peptide_name + suffix)
        if os.path.exists(candidate):
            payload = load_mdgen_like_path_file(candidate)
            if "state_paths" in payload:
                state_paths = payload["state_paths"]
            else:
                features = payload["features"]
                if features.ndim == 2:
                    return None
                state_paths = discretize_feature_paths(features, tica_model, state_centers, lag_frames=1, path_length=path_length)
            return {
                "file": candidate,
                "metrics": compute_tps_metrics(
                    reference_paths=reference_paths,
                    sample_paths=state_paths,
                    T_ref=T_ref,
                    powers=powers,
                    start_state=int(reference_paths[0, 0]),
                    end_state=int(reference_paths[0, -1]),
                ),
            }
    return None


def main():
    args = parse_args()
    rng = np.random.default_rng(args.seed)
    out_dir = os.path.dirname(args.output_json)
    if out_dir:
        os.makedirs(out_dir, exist_ok=True)

    peptides = load_tetrapeptide_directory(
        data_dir=args.data_dir,
        split_csv=args.split_csv,
        max_peptides=args.max_peptides,
        seed=args.seed,
    )
    if not peptides:
        raise SystemExit("No tetrapeptide npz files matched the requested directory/split.")
    if len(peptides) < 2:
        raise SystemExit("Need at least two peptides to run the transferable Exp 6 setup.")

    peptide_map = {peptide["name"]: peptide for peptide in peptides}
    try:
        test_names = choose_test_peptides(
            peptides,
            seed=args.seed + 17,
            test_peptide=args.test_peptide,
            max_test_peptides=args.max_test_peptides,
        )
    except ValueError as exc:
        raise SystemExit(str(exc)) from exc

    output = {
        "experiment": "run_exp6_tetrapeptide_tps",
        "data_dir": args.data_dir,
        "split_csv": args.split_csv,
        "device": args.device,
        "transfer_setup": {
            "shared_proposal": True,
            "proposal_conditioning": (
                f"sequence + {args.proposal_history_frames} recent frames "
                f"+ {max(args.proposal_history_frames - 1, 0)} deltas"
            ),
            "twist_variants": ["Take3-SelfTwist"] if args.skip_oracle_twist else ["Take3-OracleTwist", "Take3-SelfTwist"],
            "evaluation_mode": "leave_one_out" if (args.test_peptide is None and len(test_names) == len(peptides)) else ("single_held_out" if args.test_peptide is not None else "multi_held_out_subset"),
            "loaded_peptides": [peptide["name"] for peptide in peptides],
            "test_peptides": test_names,
            "max_test_peptides": args.max_test_peptides,
            "state_pair_modes": args.state_pair_modes,
        },
        "parameters": {
            "horizon_frames": args.horizon_frames,
            "lag_frames": args.lag_frames,
            "path_length": args.path_length,
            "n_states": args.n_states,
            "reward_lambda": args.reward_lambda,
            "K": args.K,
            "M": args.M,
            "n_trials": args.n_trials,
            "S_max": args.S_max,
            "n_diff_steps": args.n_diff_steps,
            "gt_samples": args.gt_samples,
            "self_ref_windows": args.self_ref_windows,
            "self_ref_batch_size": args.self_ref_batch_size,
            "reward_mode": "soft_state",
            "twist_objective": "kl",
            "balanced_pair_sampling": bool(args.balanced_pair_sampling),
            "proposal_context": f"{args.proposal_history_frames}_frame_delta",
            "proposal_history_frames": int(args.proposal_history_frames),
            "score_batch_size": int(args.score_batch_size),
            "score_lr": float(args.score_lr),
            "twist_lr": float(args.twist_lr),
            "skip_oracle_twist": bool(args.skip_oracle_twist),
        },
        "peptides": {},
    }

    for test_index, name in enumerate(test_names):
        peptide = peptide_map[name]
        train_peptides = [cand for cand in peptides if cand["name"] != name]
        if not train_peptides:
            print(f"Skipping {name}: no training peptides remain after hold-out.")
            continue

        name = peptide["name"]
        print("=" * 72)
        print(f"Tetrapeptide TPS Transfer: {name}")
        print("=" * 72)
        print(f"Training pool: {[cand['name'] for cand in train_peptides]}")

        print("Training shared transferable conditional score...")
        t0 = time.time()
        pair_x, pair_y, pair_seq, dim, context_dim, pair_sampling_meta = collect_shared_transition_pairs(
            train_peptides,
            max_pairs=args.max_pairs,
            rng=np.random.default_rng(args.seed + 101 * (test_index + 1)),
            balanced=args.balanced_pair_sampling,
            history_frames=args.proposal_history_frames,
        )
        o_model, _ = train_sequence_conditional_score(
            pair_x,
            pair_y,
            pair_seq,
            dim=dim,
            context_dim=context_dim,
            seq_dim=SEQ_FEATURE_DIM,
            n_epochs=args.score_epochs,
            batch_size=args.score_batch_size,
            lr=args.score_lr,
            hidden_dim=args.hidden_dim,
            n_layers=args.n_layers,
            device=args.device,
        )
        o_score = SequenceConditionalScore(
            o_model,
            dim=dim,
            context_dim=context_dim,
            seq_dim=SEQ_FEATURE_DIM,
            device=args.device,
        )
        o_score.history_frames = int(args.proposal_history_frames)
        shared_pair_count = int(len(pair_x))
        score_train_time = time.time() - t0
        print(f"  Shared score training time: {score_train_time:.1f}s")

        features, feature_mask = prepare_peptide_features(peptide)
        if len(features) <= max(args.horizon_frames + 1, args.lag_frames + 1):
            print(f"Skipping {name}: trajectory too short.")
            continue
        seq_feature = encode_sequence_features(peptide_conditioning_sequence(peptide))

        state_model = fit_reference_state_model(
            features,
            lag_frames=args.lag_frames,
            n_states=args.n_states,
            n_tica_dims=args.n_tica_dims,
            seed=args.seed,
        )
        peptide_result = {
            "sequence": peptide["sequence"],
            "conditioning_sequence": peptide_conditioning_sequence(peptide),
            "source_path": peptide["path"],
            "n_frames": int(len(features)),
            "training_peptides": [cand["name"] for cand in train_peptides],
            "shared_score_training": {
                "n_train_peptides": int(len(train_peptides)),
                "n_transition_pairs": shared_pair_count,
                "proposal_context_dim": int(context_dim),
                "sequence_feature_dim": int(SEQ_FEATURE_DIM),
                "history_frames": int(args.proposal_history_frames),
                "training_time_sec": float(score_train_time),
                "pair_sampling": pair_sampling_meta,
            },
            "tasks": {},
        }

        primary_mode = args.state_pair_modes[0]
        for mode_idx, pair_mode in enumerate(args.state_pair_modes):
            print(f"Selecting {pair_mode} state pair for {name}...")
            start_state, end_state, powers, pair_selection = choose_start_end_states(
                state_model["transition_matrix"],
                state_model["stationary"],
                path_length=args.path_length,
                mode=pair_mode,
            )
            try:
                task_result = evaluate_tps_task_for_peptide(
                    peptide_name=name,
                    features=features,
                    feature_mask=feature_mask,
                    state_model=state_model,
                    o_score=o_score,
                    seq_feature=seq_feature,
                    args=args,
                    start_state=start_state,
                    end_state=end_state,
                    powers=powers,
                    pair_selection=pair_selection,
                    seed_offset=args.seed + 10000 * (test_index + 1) + 1000 * mode_idx,
                    mdgen_paths_dir=args.mdgen_paths_dir,
                )
            except ValueError as exc:
                print(f"Skipping {name} / {pair_mode}: {exc}")
                continue
            peptide_result["tasks"][pair_mode] = task_result

        if not peptide_result["tasks"]:
            print(f"Skipping {name}: no task variants completed successfully.")
            continue

        primary_task = peptide_result["tasks"][primary_mode] if primary_mode in peptide_result["tasks"] else next(iter(peptide_result["tasks"].values()))
        peptide_result["primary_task"] = primary_mode if primary_mode in peptide_result["tasks"] else next(iter(peptide_result["tasks"].keys()))
        peptide_result["start_state"] = primary_task["start_state"]
        peptide_result["end_state"] = primary_task["end_state"]
        peptide_result["reference_flux"] = primary_task["reference_flux"]
        peptide_result["reference_metrics"] = primary_task["reference_metrics"]
        peptide_result["ground_truth"] = primary_task["ground_truth"]
        peptide_result["methods"] = primary_task["methods"]
        peptide_result["twist_training"] = primary_task["twist_training"]

        output["peptides"][name] = peptide_result

    save_json(output, args.output_json)
    print(f"Saved JSON to {args.output_json}")


if __name__ == "__main__":
    main()
